# Auto-generated by xilinx-modelsim-sim/run_xsim.py  (mode=behavioral)
onerror {quit -f}
vlib work
vmap work work
vmap unisim "E:/EDA/Xil18.2SimLib/unisim"
vmap unisims_ver "E:/EDA/Xil18.2SimLib/unisims_ver"
vmap unimacro "E:/EDA/Xil18.2SimLib/unimacro"
vmap unimacro_ver "E:/EDA/Xil18.2SimLib/unimacro_ver"
vmap unifast "E:/EDA/Xil18.2SimLib/unifast"
vmap unifast_ver "E:/EDA/Xil18.2SimLib/unifast_ver"
vmap secureip "E:/EDA/Xil18.2SimLib/secureip"
vmap xpm "E:/EDA/Xil18.2SimLib/xpm"
vlog -work work -L unisim -L unisims_ver -L unimacro -L unimacro_ver -L unifast -L unifast_ver -L secureip -L xpm "F:/wc.prj/pulse_mfpga/src/DXH_AI/ps2pl_cmu/sim/dut/axi_lite_slave.v" "F:/wc.prj/pulse_mfpga/src/DXH_AI/ps2pl_cmu/sim/dut/ctrl_reg_bank.v" "F:/wc.prj/pulse_mfpga/src/DXH_AI/ps2pl_cmu/sim/dut/pl_bram_comm_top.v" "F:/wc.prj/pulse_mfpga/src/DXH_AI/ps2pl_cmu/sim/dut/rx_data_path.v" "F:/wc.prj/pulse_mfpga/src/DXH_AI/ps2pl_cmu/sim/dut/tx_data_path.v" "F:/wc.prj/pulse_mfpga/src/DXH_AI/ps2pl_cmu/sim/bram_model.v" "F:/wc.prj/pulse_mfpga/src/DXH_AI/ps2pl_cmu/sim/debug2/bram_model.v" "F:/wc.prj/pulse_mfpga/src/DXH_AI/ps2pl_cmu/sim/debug2/tb_dbg.v" "F:/wc.prj/pulse_mfpga/src/DXH_AI/ps2pl_cmu/sim/debug/dbg2.v" "F:/wc.prj/pulse_mfpga/src/DXH_AI/ps2pl_cmu/sim/debug/dbg3.v" "F:/wc.prj/pulse_mfpga/src/DXH_AI/ps2pl_cmu/sim/debug/dbg_t6.v" "F:/wc.prj/pulse_mfpga/src/DXH_AI/ps2pl_cmu/sim/dut/axi_lite_slave.v" "F:/wc.prj/pulse_mfpga/src/DXH_AI/ps2pl_cmu/sim/dut/ctrl_reg_bank.v" "F:/wc.prj/pulse_mfpga/src/DXH_AI/ps2pl_cmu/sim/dut/pl_bram_comm_top.v" "F:/wc.prj/pulse_mfpga/src/DXH_AI/ps2pl_cmu/sim/dut/rx_data_path.v" "F:/wc.prj/pulse_mfpga/src/DXH_AI/ps2pl_cmu/sim/dut/tx_data_path.v" "F:/wc.prj/pulse_mfpga/src/DXH_AI/ps2pl_cmu/sim/tb_ps2pl_cmu.v"
vlog -work work "E:/EDA/Xilinx/Vivado/2018.2/data/verilog/src/glbl.v"
vopt +acc=rb -L unisim -L unisims_ver -L unimacro -L unimacro_ver -L unifast -L unifast_ver -L secureip -L xpm work.tb_ps2pl_cmu work.glbl -o tb_ps2pl_cmu_opt
vsim -c  -wlf "F:/wc.prj/pulse_mfpga/src/DXH_AI/ps2pl_cmu/sim/dut/xsim_build/run.wlf" -do {add wave -r /tb_ps2pl_cmu/*; vcd file "F:/wc.prj/pulse_mfpga/src/DXH_AI/ps2pl_cmu/sim/dut/xsim_build/run.vcd"; vcd add -r /tb_ps2pl_cmu/*; run 3ms; quit -f} tb_ps2pl_cmu_opt
