# Auto-generated by xilinx-modelsim-sim/run_xsim.py  (mode=behavioral)
onerror {quit -f}
vlib work
vmap work work
vmap unisim "E:/EDA/Xil18.2SimLib/unisim"
vmap unisims_ver "E:/EDA/Xil18.2SimLib/unisims_ver"
vmap unimacro "E:/EDA/Xil18.2SimLib/unimacro"
vmap unimacro_ver "E:/EDA/Xil18.2SimLib/unimacro_ver"
vmap unifast "E:/EDA/Xil18.2SimLib/unifast"
vmap unifast_ver "E:/EDA/Xil18.2SimLib/unifast_ver"
vmap secureip "E:/EDA/Xil18.2SimLib/secureip"
vmap xpm "E:/EDA/Xil18.2SimLib/xpm"
vlog -work work -L unisim -L unisims_ver -L unimacro -L unimacro_ver -L unifast -L unifast_ver -L secureip -L xpm "F:/wc.prj/pulse_mfpga/src/DXH_AI/ps2pl_cmu/sim/run_stage/axi_lite_slave.v" "F:/wc.prj/pulse_mfpga/src/DXH_AI/ps2pl_cmu/sim/run_stage/bram_model.v" "F:/wc.prj/pulse_mfpga/src/DXH_AI/ps2pl_cmu/sim/run_stage/ctrl_reg_bank.v" "F:/wc.prj/pulse_mfpga/src/DXH_AI/ps2pl_cmu/sim/run_stage/pl_bram_comm_top.v" "F:/wc.prj/pulse_mfpga/src/DXH_AI/ps2pl_cmu/sim/run_stage/rx_data_path.v" "F:/wc.prj/pulse_mfpga/src/DXH_AI/ps2pl_cmu/sim/run_stage/tb_ps2pl_cmu.v" "F:/wc.prj/pulse_mfpga/src/DXH_AI/ps2pl_cmu/sim/run_stage/tx_data_path.v"
vlog -work work "E:/EDA/Xilinx/Vivado/2018.2/data/verilog/src/glbl.v"
vopt +acc=rb -L unisim -L unisims_ver -L unimacro -L unimacro_ver -L unifast -L unifast_ver -L secureip -L xpm work.tb_ps2pl_cmu work.glbl -o tb_ps2pl_cmu_opt
vsim -c  -do {run 4ms; quit -f} tb_ps2pl_cmu_opt
