`timescale 1ns / 1ps

// ============================================================================
// mfpga_clk_gen.v
// Clock generator wrapper for the pulse_mfpga (DXH_AI) design.
//
// Encapsulates the Xilinx Clocking Wizard IP "mfpga_clk_gen_ip" (MMCM,
// generated by Vivado 2018.2 for part xc7z020clg400-2).
//
//   Input : i_fpga_ref_clk_50m  -- 50 MHz single-ended reference clock
//   Output: 6 derived clocks + raw locked + global synchronous reset
//
// Reset scheme (mirrors legacy clk_gen_top.v):
//   The Clocking Wizard IP has no reset input (USE_RESET=false). The global
//   reset is derived from the MMCM "locked" signal: an active-high,
//   asynchronous-assert / synchronous-release 3-stage synchronizer clocked by
//   the slowest output (20 MHz), then driven globally through a BUFG.
//
//   reset = 1  -> reset active   (MMCM not locked)
//   reset = 0  -> reset released (MMCM locked)
// ============================================================================
module mfpga_clk_gen(
    input  wire i_fpga_ref_clk_50m,

    // ---- derived clocks ----
    output wire o_clk_160m,       // 160 MHz  LVDS DDR fast clock
    output wire o_clk_40m,        //  40 MHz  LVDS DDR slow clock (160/4)
    output wire o_clk_200m,       // 200 MHz  LVDS SelectIO reference
    output wire o_clk_125m,       // 125 MHz  RGMII
    output wire o_clk_125m_90d,   // 125 MHz  RGMII TX (90 deg phase shift)
    output wire o_clk_20m,        //  20 MHz  GPIB

    // ---- status / control ----
    output wire o_locked,         // raw MMCM locked signal
    output wire o_reset           // global reset, active-HIGH (locked-sync, BUFG)
);

//===================== internal signals =====================
wire mmcm_locked;          // MMCM raw locked
wire reset_internal;       // BUFG input reset (pre-BUFG)

//===================== clock IP instantiation =====================
// INST_TAG  mfpga_clk_gen_ip
mfpga_clk_gen_ip u_mfpga_clk_gen_ip (
    // Clock in ports
    .clk_in1  (i_fpga_ref_clk_50m),
    // Status and control signals
    .locked   (mmcm_locked),
    // Clock out ports
    .clk_out1 (o_clk_160m),
    .clk_out2 (o_clk_40m),
    .clk_out3 (o_clk_200m),
    .clk_out4 (o_clk_125m),
    .clk_out5 (o_clk_125m_90d),
    .clk_out6 (o_clk_20m)
);

assign o_locked = mmcm_locked;

//===================== global reset synchronizer =====================
// 3-stage synchronizer: async assert on unlock, sync release on lock.
// Clocked by the slowest output clock (20 MHz) for a robust, glitch-free reset.
reg [2:0] locked_sync;

always @(posedge o_clk_20m or negedge mmcm_locked) begin
    if (!mmcm_locked)
        locked_sync <= 3'b111;                              // MMCM not locked -> reset active
    else
        locked_sync <= {locked_sync[1:0], 1'b0};            // MMCM locked   -> shift in 0 (release)
end

assign reset_internal = locked_sync[2];

//===================== BUFG-driven global reset =====================
// Low-skew global distribution of the reset.
BUFG u_bufg_reset (
    .I (reset_internal),
    .O (o_reset)
);

endmodule
